name: Build Debian Package

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev gcc
          sudo add-apt-repository -y ppa:rockowitz/ddcutil
          sudo apt-get update
          sudo apt-get install -y ddcutil libddcutil-dev

      - name: Build Debian package
        run: ./build-deb.sh

      - name: Upload Debian package as release asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./build/luminance.deb
          release_id: ${{ github.event.release.id }}
          repository: ${{ github.repository }}
