name: Upload release assets

permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build-deb:
    name: Build and upload deb package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Initialize ddcbc-api git submodule
        run: git submodule update --init ddcbc-api

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:rockowitz/ddcutil
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev ddcutil libddcutil-dev libglib2.0-dev gcc

      - name: Build package
        run: ./build-deb.sh

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/luminance.deb
          asset_name: luminance-${{ github.event.release.tag_name }}.deb
          tag: ${{ github.ref }}

  build-rpm:
    name: Build and upload rpm package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Initialize ddcbc-api git submodule
        run: git submodule update --init ddcbc-api

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:rockowitz/ddcutil
          sudo apt-get update
          sudo apt-get install -y gcc libgtk-3-dev ddcutil libddcutil-dev rpm

      - name: Build package
        run: ./build-rpm.sh

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/luminance.rpm
          asset_name: luminance-${{ github.event.release.tag_name }}.rpm
          tag: ${{ github.ref }}
