on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Initialize ddcbc-api git submodule
        run: git submodule update --init ddcbc-api

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:rockowitz/ddcutil
          sudo apt-get update
          sudo apt-get install -y gcc libgtk-3-dev ddcutil libddcutil-dev

      - name: Build Debian package
        run: ./build-deb.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload deb package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/luminance.deb
          asset_name: luminance.deb
          tag: ${{ github.ref }}
